### ISSUE TITLE
Feed rate units incorrect in kiri:moto for Onshape?

### ISSUE THREAD

**Issue by roscopetracula** [GridSpace/gridspace.github.io#1]
I'm not sure if this  is a real issue or just a confusion on my part, but the default feed rates in Kiri:Moto for Onshape are so fast that they have made me nervous i'm going to break something -- they defaults are 1000 mm/s. I'm working on a hobby machine (x-carve) so rates around 50-100 inches/min (about 20-40mm/s) seem familiar to me. I'm wondering if the units are just mislabeled in the tool tips, or if the default speeds are set unreasonably high, or if professional machines can actually go that fast...

Anyway, great work. The Onshape integration is very cool.

**Comment by roscopetracula** [comment]
Quick follow up: I tried changing the values to 35mm/s (2100 mm/min, 82in/min), and when I tried running the gcode, the machine basically didn't move. This leads me to believe the units in the tool tips are incorrect-- should it be *mm/min* rather than *mm/s*?

Looking forward to hearing back about this-- until the units are nailed down, I'm hesitant to use use this tool for fear of breaking tools, getting bad cuts, etc.

**Comment by stewartoallen** [comment]
The tool tips are wrong.  It should be millimeters / minute.  Copy/paste error.  Thanks for the heads up.  I'm pushing an update now.

**Comment by stewartoallen** [comment]
Ok, I'll take a look

**Comment by stewartoallen** [comment]
units and feeds have had major re-work.  at present, there are no known bugs with it.
