### ISSUE TITLE
No Cut-Out Tabs in Finishing

### ISSUE THREAD

**Issue by Andreas-X-Carve** [GridSpace/gridspace.github.io#11]
Hi Stewart,

here is a new bug. When I use cutout tabs they just work in roughing and only waterline in finishing. Linear x and linear y do not recognize the tabs and cut them away.
![bildschirmfoto 2017-02-16 um 14 06 25](https://cloud.githubusercontent.com/assets/24457313/23022452/22e1aa6e-f451-11e6-9a8c-a117b3b59fa1.png)

**Comment by stewartoallen** [comment]
thanks for the report.  I see other things that could be cleaned up in that output as well.

**Comment by stewartoallen** [comment]
fixed a long time ago
