### ISSUE TITLE
Linear x and Linear y with ballmill tool

### ISSUE THREAD

**Issue by Andreas-X-Carve** [GridSpace/gridspace.github.io#12]
finishing is cutting into object with a ballmill tool. Toolpath is to close to the object.
![bildschirmfoto 2017-02-18 um 12 33 56](https://cloud.githubusercontent.com/assets/24457313/23093057/23089348-f5d9-11e6-89bd-e98c8eb341f7.png)

**Comment by stewartoallen** [comment]
Is this a new issue or has it always been like that for you?

**Comment by Andreas-X-Carve** [comment]
I do not know cause i never used ballmills. I just checked if the tool size makes any difference but the distance to the object stays the same (only in ballmill selection). For example even with a 10mm bit the linear tool path is still right on the surface and the waterline is correct.
![bildschirmfoto 2017-02-18 um 15 36 26](https://cloud.githubusercontent.com/assets/24457313/23093950/304aa458-f5f0-11e6-9f27-063d59f3385d.png)

**Comment by stewartoallen** [comment]
when you say it's cutting into the object, are you saying that based on an actual cut or the screenshot?

**Comment by Andreas-X-Carve** [comment]
It cut into the object. That's why i checked the paths. But i'm going to try again to make sure.

**Comment by stewartoallen** [comment]
ok, I appreciate the debugging

**Comment by Andreas-X-Carve** [comment]
Your welcome.

**Comment by Andreas-X-Carve** [comment]
so...it is actually cutting into the object. Especially the y axis. (see picture).
Linear is also cutting quite deep into the bottom. (see screenshot)
It also generated some weird toolpaths in generally but i chance the bit to endmill the false paths disappear. 
![bildschirmfoto 2017-02-18 um 16 50 38](https://cloud.git
https://photos.google.com/photo/AF1QipPDNl--qdIE70tx4K5ZjA4POcRhZHM36MaoU_u
![img_20170218_164209](https://cloud.githubusercontent.com/assets/24457313/23094509/c3d9096c-f5fa-11e6-9b2c-016b0304b05c.jpg)
zhubusercontent.com/assets/24457313/23094493/6692a6f0-f5fa-11e6-834c-cdd4d4a472e1.png)

![bildschirmfoto 2017-02-18 um 16 40 23](https://cloud.githubusercontent.com/assets/24457313/23094475/f890f3b4-f5f9-11e6-9c20-dde8edcd65c6.png)

**Comment by Andreas-X-Carve** [comment]
![bildschirmfoto 2017-02-18 um 16 50 38](https://cloud.githubusercontent.com/assets/24457313/23094520/e28538e0-f5fa-11e6-93e5-5b0c06e93904.png)

**Comment by stewartoallen** [comment]
ok, so it's limited to ballmill.  I will try to reproduce.

**Comment by Andreas-X-Carve** [comment]
Hi Stewart. I did some more testing and here my observations.
Linear xy with a endmill works fine but does not remove marks from the roughing pass(picture 1) I have at least to but 0.5mm to the "leave stock" then it works fine (picture 2).
https://photos.google.com/photo/AF1QipN9mFO9mr6rIG9MY3d6wuQgTMFI5M0sMJRW8YW
https://photos.google.com/photo/AF1QipPfbZVaxohpCXrESyoE_UJ4oZ-pySXpUFCgCylJu

Linear with an Ballmill works quite good on the x axis but the y axis removes to much on steep angles (see picture 3 and 4
https://photos.google.com/photo/AF1QipOWjxBBZtqVCOGryCpp4KFraPheYVHHBRVbW2t
https://photos.google.com/photo/AF1QipOWjxBBZtqVCOGryCpp4KFraPheYVHHBRVbW2t77).

**Comment by Andreas-X-Carve** [comment]
![img_20170221_154040](https://cloud.githubusercontent.com/assets/24457313/23169965/f92dba54-f84d-11e6-9265-3d088f24be2b.jpg)
![img_20170221_154124](https://cloud.githubusercontent.com/assets/24457313/23169966/f9312054-f84d-11e6-8d60-1687f5393b3a.jpg)
![img_20170221_154144](https://cloud.githubusercontent.com/assets/24457313/23169964/f92a3aaa-f84d-11e6-9215-ca9216f347a2.jpg)
![img_20170221_154157](https://cloud.githubusercontent.com/assets/24457313/23169962/f91f9078-f84d-11e6-8cf5-0a7dcf434185.jpg)

**Comment by Andreas-X-Carve** [comment]
by the way! Did you change something on the linear finishing...it looks like the path close to the bottom are better.

**Comment by Andreas-X-Carve** [comment]
and i forgot. With the ballmill all roughing marks get removed without adjusting the leave stock. The ballmill paths are in generally closer too the object.

**Comment by stewartoallen** [comment]
Linear finishing hasn't changed.  Perhaps you have some backlash in Z?  For more vertical faces, you will need to use a smaller step over to get a cleaner finish.

**Comment by Andreas-X-Carve** [comment]
Ok. I think Kiri Moto takes the STL object beneath quite into account. Because some objects get better, smoother pats than others. That might be the reason i thought linear finishing has changed.

**Comment by stewartoallen** [comment]
The latest release does a substantially better job with ball and taper mills.
