### ISSUE TITLE
Waterline ballmill vs. endmill

### ISSUE THREAD

**Issue by Andreas-X-Carve** [GridSpace/gridspace.github.io#13]
Waterline toolpath stays at the same distance from object. (Ballmill should be closer because of the differnt distance of the cutting edge).

**Comment by stewartoallen** [comment]
Waterline does not account for tool geometry.  Only linear finishing does.  I don't expect this to change anytime soon as that would require a rewrite of waterline.

**Comment by Andreas-X-Carve** [comment]
Ok. Thanks for the information. So will not spent more time trying to figure it out.

**Comment by stewartoallen** [comment]
it's on my todo list for the future.  I will close this issue since it's working as expected.
