### ISSUE TITLE
Toolpath incorrect - Crash / Collision

### ISSUE THREAD

**Issue by rqhub** [GridSpace/gridspace.github.io#14]
Got a toolhead crash. It's trying to cut from the bottom, before doing the top part (or it though it was done???). The STL has no errors. I wonder if the cutout tabs on complex shapes, ie, ones with many internal holes (in this one i've added to my model internal bridges so i can mill it all in one go) makes the algos bug.

Pictures worth a thousand words.
![capture d ecran 2017-04-03 a 06 29 19](https://cloud.githubusercontent.com/assets/13416968/24594584/546a3d6c-1837-11e7-828c-3f1292856ae6.png)
![capture d ecran 2017-04-03 a 06 28 41](https://cloud.githubusercontent.com/assets/13416968/24594585/54a58cb4-1837-11e7-97db-3a547d78c1db.png)
![capture d ecran 2017-04-03 a 06 26 14](https://cloud.githubusercontent.com/assets/13416968/24594586/54c954be-1837-11e7-9174-ca041fd2ca00.png)

**Comment by rqhub** [comment]
Another collision. In pocket mode. Layers are 0.33 mm deep, and step over 0.75 (these make the optimal speed for my flimsy diy machine), but about midway (see line 9096 in the gcode), when it has to finish the pockets, it starts from the outside instead of starting from the inside, and this generates a (big) collision. Could you rollback to - or make available the - previous versions of the toolpathing algo please ?

[collision.nc.txt](https://github.com/GridSpace/gridspace.github.io/files/895239/collision.nc.txt)
![capture d ecran 2017-04-05 a 08 24 52](https://cloud.githubusercontent.com/assets/13416968/24691093/11053866-19da-11e7-8036-de2b7a326fb9.png)
![capture d ecran 2017-04-05 a 08 24 43](https://cloud.githubusercontent.com/assets/13416968/24691095/1167c328-19da-11e7-99cd-b99cf4fe6327.png)
![capture d ecran 2017-04-05 a 08 24 41](https://cloud.githubusercontent.com/assets/13416968/24691094/1146004e-19da-11e7-9051-06174fb4ce18.png)

**Comment by rqhub** [comment]
The problem seems to dissapear if i disable cutout tabs.

**Comment by stewartoallen** [comment]
Can you share the STL and settings so that I can replicate / fix?  

sa@grid.space

thanks

**Comment by stewartoallen** [comment]
Disable depth-first to work around this for now.  Rechecking the depth packing algo this weekend.

**Comment by rqhub** [comment]
thanks !

**Comment by stewartoallen** [comment]
I found and fixed the nesting defect that caused this collision.  Thanks for the bug report.  Please verify and close the issue.

**Comment by rqhub** [comment]
Looks good to me. Many thanks.

**Comment by rqhub** [comment]
It's back. Cutout tabs are messing things up. Cf. Screenshots.
Depth first or not has no influence (tried the 4 cases)

![capture d ecran 2017-04-18 a 17 28 07](https://cloud.githubusercontent.com/assets/13416968/25136165/e3e96afe-245c-11e7-9378-9bc2743170bc.png)

**Comment by stewartoallen** [comment]
This is a separate issue with tab generation vs depth-first, but the same outcome.  I've seen this before and have an idea how to fix it.

**Comment by stewartoallen** [comment]
also, please send the STL so I have a good/repeatable test case.  thanks.

**Comment by stewartoallen** [comment]
a fix for this has been checked into github.  will push a new version no later than tomorrow.  verify locally and lmk.

**Comment by rqhub** [comment]
Checked. Works. Cheers.

**Comment by rqhub** [comment]
that lochness bug is back :-) 

seems to work fine during the slicing, then when going to preview or export, things get weird

got bigger tools now, switched from a dremel to a 400W spindle ...

 a crash on those will make damage

[Vacuum Plate.STL.zip](https://github.com/GridSpace/gridspace.github.io/files/1594586/Vacuum.Plate.STL.zip)


<img width="852" alt="capture d ecran 2017-12-30 a 18 36 32" src="https://user-images.githubusercontent.com/13416968/34455877-3881d120-ed91-11e7-9159-a52985e1a903.png">
![capture d ecran 2017-12-30 a 18 36 17-](https://user-images.githubusercontent.com/13416968/34455977-852efac8-ed93-11e7-9c4e-ba3267a07dcc.jpg)

**Comment by stewartoallen** [comment]
I'm not able to replicate.  Can you highlight the collision?

video here: https://www.youtube.com/watch?v=qq0YeQoCYos

![screen shot 2018-01-03 at 3 30 03 pm](https://user-images.githubusercontent.com/554275/34538609-058a2684-f09b-11e7-945a-a74210fec417.png)

**Comment by rqhub** [comment]
Hey stewart,

Sorry, i'm far from my computer now,

The algo lost a big chunk of the toolpathing once i clicked on export. Cf. Difference between slice result/yellow and preview/blue.

It's weird, as if the export window ate the toolpath lines that were behind it.

It might be something new. 

Or issues with memory / garbage collector firing up too early?

Best

Ramez

**Comment by stewartoallen** [comment]
you are correct. I see that now. Will look into a fix.

**Comment by stewartoallen** [comment]
fixed by https://github.com/GridSpace/apps/commit/ac96381dfabec65cc7ce58a7b274bf3e3373df51
