### ISSUE TITLE
Tolerances / Holes

### ISSUE THREAD

**Issue by rqhub** [GridSpace/gridspace.github.io#15]
Sometimes holes of about the milling bit diam are not taken into account. 
Seems to happen with holes + countersunk
Made tries. The holes are 3.25mm.
With a milling bit of 2.88mm it takes it (that's a 0.74mm difference !!)
Above it won't take it.
![capture d ecran 2017-04-18 a 17 41 39](https://cloud.githubusercontent.com/assets/13416968/25136866/d3675126-245e-11e7-949f-451ee5c0b5e1.png)
![capture d ecran 2017-04-18 a 17 41 06](https://cloud.githubusercontent.com/assets/13416968/25136867/d3a4b8fe-245e-11e7-8c5b-d713d063e620.png)

**Comment by stewartoallen** [comment]
The hole diameter has to be within 0.1% of the bit diameter to match and trigger drilling code.  Otherwise it will rough out the pocket normally.
