### ISSUE TITLE
Gcode output time estimate seems off by a factor of 60

### ISSUE THREAD

**Issue by jwhite66** [GridSpace/gridspace.github.io#16]
When exporting a part to gcode for CNC milling, using a generic LinuxCNC device and a feed rate of 400, I get time estimates that seem ridiculous.  103 hours for a part that cut in 2; 11 hours for a part that cuts in 20.  I can't say precisely, but it feels like it's off by a factor of 60.  I suspect it's related to issue #1.

**Comment by stewartoallen** [comment]
fixed in recent releases
