### ISSUE TITLE
Feature Request: Generate curved features as G02 arc commands

### ISSUE THREAD

**Issue by jeromio** [GridSpace/gridspace.github.io#17]
It would be ideal for Kiri to translate arcs in drawings to G02 arc commands rather than stair steps of individual G01 commands. I'm imagining something like a geo-arc.js (at least from the perspective of someone who doesn't really understand how the code works 😎)

**Comment by stewartoallen** [comment]
it would require an inference engine that detects an arc-like series of points. computationally expensive, but doable.  i'm adding this to the "future nice to have list", but closing as an issue. thanks!
