### ISSUE TITLE
Cam mode Kiri ignores simple carve..perhaps

### ISSUE THREAD

**Issue by Butchstang** [GridSpace/gridspace.github.io#18]
![kiri small slot](https://user-images.githubusercontent.com/61163092/74681931-8a0c8800-51bc-11ea-97d2-9d00aa1ed3b2.jpg)
Hello. Just trying to cut this part. Kiri:moto does a fantastic job on all of it but fails to cut the slot.
It is a fairly small part. I am using a 1/8 ( 3.175mm) inch ball mill. I thought it might just run along the slot but it only seems to recognise it with the finishing x-y grid. This is OK but is not an accurate way to cut a slot... any tips.

**Comment by stewartoallen** [comment]
Are you doing this as a "pocket only" operation?

**Comment by Butchstang** [comment]
Hello,
No, as I want to cut the profile. I have tried with the pocket only function but had the same missing slot.
I’m using Parameters below. Depth first, ease down. Ive tried it with and without the finishing cut. 
The second image shows the finishing cut dipping into the slot.






Peter Canham

07938 096 529

ystabl@mac.com

**Comment by stewartoallen** [comment]
The latest release fixes most of these issues.  That slot will remain very difficult to detect with current methods.  There are coming improvements that could completely address it.  But I'm not certain it's an iron-clad solution to all such cases.
