### ISSUE TITLE
slow to slice and wont export

### ISSUE THREAD

**Issue by onsitespouting** [GridSpace/gridspace.github.io#2]
"aww snap,something went wrong" this is the message i get

**Comment by stewartoallen** [comment]
can you share the link to the model that's causing this along with a snapshot of your settings?  this usually means chrome is running out of memory.

**Comment by onsitespouting** [comment]
https://cad.onshape.com/documents/5726eb44b6327f7e03b3f9a5/w/c47134ae2e49acb4255388c2/e/b54cd0ad016d5285a1fafa38

On 12 May 2016 at 07:48, Stewart Allen <notifications@github.com> wrote:

> can you share the link to the model that's causing this along with a
> snapshot of your settings? this usually means chrome is running out of
> memory.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GridSpace/gridspace.github.io/issues/2#issuecomment-218569192>
>



-- 
Dear



<https://www.facebook.com/onsitespoutingnz>

Thankyou

Mark Rountree

www.onsitespouting.co.nz
mob       0274  776886
call free  0508  776886
onsitespouting@gmail.com

You can rate our service here!
<http://www.nocowboys.co.nz/businesses/Onsite-Spouting-/>



This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
Please note that any views or opinions presented in this email are solely
those of the author and do not necessarily represent those of the company.
Finally, the recipient should check this email and any attachments for the
presence of viruses.

**Comment by stewartoallen** [comment]
I was able to slice this in Chrome and Safari in both CAM and FDM mode with default settings on a Mac with 8GB RAM.  Can you share a screenshot of the right hand panel with your settings?

**Comment by onsitespouting** [comment]
I tried twice to send a screen shot but it won't go through,I'm replying
direct to your emails with screenshot as attachment.

**Comment by stewartoallen** [comment]
that doesn't appear to be working, either.  I suggest either dropping an image onto the github comment field [for this issue](https://github.com/GridSpace/gridspace.github.io/issues/2) or send a separate email to sa@grid.space with the image attachment.

thanks for the report.  sorry about the hassle.

**Comment by onsitespouting** [comment]
I'll send to sa@gridspace

Thankyou
Mark Rountree
Onsite Spouting ltd
www.onsitespouting.co.nz
Ph 0274 776 886
Feel Free to Join us On facebook

**Comment by stewartoallen** [comment]
This is almost certainly a memory constraint problem.  I will continue to optimize the memory footprint of Kiri:Moto.  And I hope to add server-side processing for larger models and memory-bound clients.
