### ISSUE TITLE
centreing parts on print bed

### ISSUE THREAD

**Issue by onsitespouting** [GridSpace/gridspace.github.io#3]
have tried arrange,moved part to far corner but it still prints at front left cnr.The part has a flat  bottom with fillets and its reading the flat bottom ,then when it gets to far up on the print its moving sideways as the stopper hits the side.result is a slanting part.

**Comment by stewartoallen** [comment]
where the toolpath is centered depends on whether or not you have "origin center" checked under the output menu on the right hand side.  Also, there is a bug with re-slicing a part that was only moved and hasn't also been rotated, scaled or re-imported.
