### ISSUE TITLE
Sliced laser output smaller dimensions

### ISSUE THREAD

**Issue by dandumit** [GridSpace/gridspace.github.io#4]
Nice application.
I have tried it for some stl files and output svg slices are scaled down .
Am I doing something wrong ? 

Please see example files. First one gives dimenstions that it should have  and the last one it's the STL file.

![motor mount draw](https://cloud.githubusercontent.com/assets/670552/18501566/1cf0ec9e-7a5a-11e6-8d26-ec1d46c91095.jpg)
[motor-mount-plate-nema-17-stepper-moto.zip](https://github.com/GridSpace/gridspace.github.io/files/471377/motor-mount-plate-nema-17-stepper-moto.zip)

Daniel

**Comment by stewartoallen** [comment]
Hi Daniel,

All output is in millimeters.  How scaled down is it?  Also, note under “process” the “cut offset”.  



this allows you to adjust for beam width.

Regards,
Stewart

**Comment by dandumit** [comment]
OVerall piece should have max dimensions 82 X 39.5 mm.

SVG file generated has 23.421 X 11.424 mm.
Aproximative 3.3 times smaller.
thank you,
DAniel

**Comment by dandumit** [comment]
Output dimensions are about 3.3 times smaller.
I will close here and I will try to open a bug.

**Comment by stewartoallen** [comment]
Just pushed a new version that should fix this. Please close the issue if verified.

**Comment by stewartoallen** [comment]
fixed
