### ISSUE TITLE
Step Over Roughing

### ISSUE THREAD

**Issue by Andreas-X-Carve** [GridSpace/gridspace.github.io#6]
If you change the stepover in roughing (for example 0.8 or 0.9) the program generates impossible cuts. The CNC will crash because it cuts into full material.

**Comment by stewartoallen** [comment]
Can you supply an STL and a full set of parameters to duplicate this?

**Comment by Andreas-X-Carve** [comment]
Hi Stewart,

screenshot of the settings. 

Thank you very much for your program. It's brilliant and i use it a lot recently. I'm gonna update you...cause i already stumbled over a couple of bugs in the last weeks but I did not report them cause i was in a production rush. I'm going to let you know as soon as they occur again.

Thanks a lot again...i really appreciate your efforts.

P.S.: I can't attach the stl file here and with the mail i get a mail delivery fail note on the replay....?

![bildschirmfoto 2016-12-08 um 18 13 58](https://cloud.githubusercontent.com/assets/24457313/21020641/9bb82d7c-bd75-11e6-99f4-ecf892d5fa60.png)

**Comment by stewartoallen** [comment]
please email the STL to sa@grid.space and I'll take a look

**Comment by stewartoallen** [comment]
I have reproduced your problem but don't have a solution yet.  In the meantime, please uncheck "depth first" and you will get a safe cut path.

**Comment by Andreas-X-Carve** [comment]
Ok. Thanks.
